<html>
<head><title>KeywordGenerated</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<body>
<table border="0" cellspacing="1" cellpadding="0" width="740" bgcolor="#669900" align="center">
<form action="KeywordGenerated.php" method="post">
  <tbody>
  <tr>
    <td bgcolor="#e6f3e4" valign="top" align="left">
      <table border="0" cellspacing="0" cellpadding="0" width="758">
        <tbody>
        <tr>
          <td class="STYLE3" height="20" align="middle">
            <h1>KeywordGenerated by: dreamhack</h1></td></tr>  
       </tbody></table>
      <table border="0" cellspacing="0" cellpadding="0" width="738" align="center">
        <tbody>
        <tr>
          <td valign="center" align="middle"><table border="0" cellspacing="5" bgcolor="#f0f0f0">
            <tbody><tr>
              <td>ListA：<br>
                <textarea rows="25" name="listA"><?php header("content-Type: text/html; charset=Utf-8");  $listA = preg_split('/\r\n/',$_POST['listA']);   foreach($listA as $name){
   echo $name."\n";
} ?></textarea></td>
              <td>ListB：<br>
                <textarea rows="25"  name="listB"><?php   header("content-Type: text/html; charset=Utf-8"); $listB = preg_split('/\r\n/',$_POST['listB']);   foreach($listB as $name){
   echo $name."\n";
} ?></textarea></td>
              <td> 生成关键词：<br>
              <textarea rows="25" cols="40" name="product_combination"><?php header("content-Type: text/html; charset=Utf-8");
	$listA = preg_split('/\r\n/',$_POST['listA']);
	$listB = preg_split('/\r\n/',$_POST['listB']);
	foreach($listA as $nameA){

		foreach ($listB as $nameB) {

			$KeywordGenerated = $nameA.$nameB;
			if ($KeywordGenerated == $nameA || $KeywordGenerated == $nameB) {
	
			}else{
				$_str =preg_replace("/\s|　/","",$KeywordGenerated); 
				echo $_str."\n";
			}
		}
	}
	?>
                </textarea></td>
            </tr>
            <tr>
            <td><input type="submit" name="Submit" value="提交"><input type="reset" name="" ame="Reset" valur="重置"></td>
            </tr>
          </tbody></table></td></tr></tbody></table>
</form>
</body>
</html>
